mod_dnssd.c: Use ap_unixd_setup_child
This fixeds an undefined reference to unixd_setup_child in the
compiled module.  This looks to have changed in httpd-2.3.2 dev:
20090130.0 (2.3.2-dev)  Add ap_ prefix to unixd_setup_child().